### ISSUE TITLE
Button not appear in the status box sometimes

### ISSUE THREAD

**Issue by swanhtet1992** [swanhtet1992/MagicButton#3]
Have to refresh the facebook to see the button.

**Comment by setkyar** [comment]
It's appear well on mine :thought_balloon: I try over 10 times, I am on linux. I am not sure about window :smile:

**Comment by swanhtet1992** [comment]
တစ်ခါတစ်လေမှဗျ... ဘာဖြစ်တာလဲ သိဘူး... ဒါဆိုရင်တော့ ပြဿနာမရှိလောက်ဘူးထင်ပါတယ်။

**Comment by setkyar** [comment]
I know it now bro, I will fix it. Because we are just try to append only. We never wait for ready document. That is why it's not appear on slow connection.
