### ISSUE TITLE
Choose default converter

### ISSUE THREAD

**Issue by dev-myatminsoe** [swanhtet1992/MagicButton#4]
Allowing users to choose default converter.

**Comment by swanhtet1992** [comment]
Ah, sorry. I don't get it bro. What's the issue?

**Comment by dev-myatminsoe** [comment]
Actually not an issue bro. I want to choose default converter, Zawgyi -> Unicode.

**Comment by swanhtet1992** [comment]
I see. You mean ability to set default converter? But.... since you can choose the converter type just by one click in v0.0.3, I think it is not necessary.

**Comment by swanhtet1992** [comment]
#5 solve this.
